from __future__ import annotations


LANGUAGE_MONITORING_DOMAINS = [
    "activation",
    "continuation",
    "assertion_laundering",
    "authorization",
]

CONTINUATION_PHRASES = {
    "en": ("continue", "go on", "carry on", "proceed", "keep going", "next step"),
    "zh": ("继续", "继续吧", "接着", "接着做", "往下做", "下一步"),
    "de": ("weiter", "mach weiter", "weiter machen", "fortfahren"),
    "fr": ("continue", "continuer", "continuez", "poursuis", "allez-y"),
    "es": ("continua", "continúa", "sigue", "adelante", "prosigue"),
    "pt": ("continua", "continuar", "prossiga", "siga", "vai em frente"),
    "ja": ("続けて", "続行", "進めて", "次へ", "続きをお願いします"),
    "ko": ("계속", "계속해", "계속 진행", "진행해", "다음 단계"),
}

AUTHORIZATION_REPLIES = {
    "yes",
    "y",
    "go ahead",
    "do it",
    "approved",
    "proceed",
    "ok",
    "okay",
    "si",
    "sí",
    "oui",
    "ja",
    "sim",
    "可以",
    "同意",
    "はい",
    "네",
}

AUTHORIZATION_DENIAL_SIGNALS = (
    "no",
    "nope",
    "nein",
    "non",
    "nao",
    "não",
    "not approved",
    "decline",
    "denied",
    "don't",
    "dont",
    "do not",
    "local only",
    "locally only",
    "don't push",
    "dont push",
    "do not push",
    "not push",
    "don't deploy",
    "dont deploy",
    "do not deploy",
    "don't release",
    "dont release",
    "do not release",
    "不要推送",
    "别推送",
    "不要发布",
    "别发布",
    "不要部署",
    "别部署",
    "不",
    "不行",
    "不可以",
    "否",
    "只做本地",
    "只继续本地",
    "本地工作",
    "はい?",
    "いや",
    "아니요",
)

HIGH_AUTONOMY_SIGNALS = (
    "修复",
    "完成",
    "验证",
    "测试",
    "提交",
    "推送",
    "发布",
    "删除",
    "移除",
    "清空",
    "截断",
    "fix",
    "complete",
    "verify",
    "test",
    "commit",
    "push",
    "delete",
    "remove",
    "drop",
    "truncate",
    "force push",
    "force-push",
    "merge",
    "rebase",
    "tag",
    "publish",
    "archive",
    "release",
    "deploy",
)

EXTERNAL_SIDE_EFFECT_SIGNALS = (
    "推送",
    "发布",
    "部署",
    "删除",
    "移除",
    "清空",
    "截断",
    "push",
    "delete",
    "remove",
    "drop",
    "truncate",
    "force push",
    "force-push",
    "merge",
    "rebase",
    "tag",
    "publish",
    "archive",
    "release",
    "deploy",
)
